http://www.eltech.ru

* Преподаватели
[[mailto:zaochnikleti@mail.ru][email]]

Пароль: popovizobrelradio (попов изобрел радио)

Елена Ивановна Беседина
[[mailto:elivbesedina@mail.ru][email]]

** Заметки
Сделать задания до 25.10.16

** Кафедра

*** Кабинет
3319

*** Расписание
закрывается в 17:00

*** Телефон
356-45-47

*** Заметки
Сделать тест до 25.09.15.

* Встречу начал
Зам декана открытого фак по заоч форме обучения

* Лекцию начал

** Заместитель деканата открытого факультета по заочной форме обучения
Шануренко Александр Констанинович

* Деканат

** Адрес
3309 3 этаж 3 корпус

** Расписание
пон, вт с 5 до 7
пон, чт с 5 до 7

** Секретари
- Гуком Юлия Васильевна
  
с 13 до 19 часов

** Телефоны деканата
234-39-37
346-48-37

** Адрес
192-376 СПБ улица Профессора попова, дом 5, СБП-ГТУ Лэти открытый факультет (деканат) ПФ

** Почта
of@yandex.ru

** Материал
Методический материал на сайте кафедры для заочной формы обучения

** Библиотека
Доступна после внесения в базу данных универстита.

*** Требования:
- читательский билет в отделе литературы
  1 корпус 2 эт комната 1248

** Телефон
346-33-95

группа 6002 кафедра электроного прибора строения

6005
6006

Вычислительная техника

|   | ия | ист | инж информат | алгебра | химия | мак | графика | графика... |
|---+----+-----+--------------+---------+-------+-----+---------+---|
|   |    |     |              |         |       |     |         |   |

* 2 доска

ФИБС ПМИГ читаемые дисциплины

"Инженерная графика"

Вар. 1-40

vnveresov@etu.ru

Читаемые дициплины

12 янв - 31 янв сессия (20 дней) все учебные дни кроме воскресенья с 10 до 16 часов

* Курсы программирования

** Материалы

Раздаточные материалы 1
Раздаточные материалы 2

Курсовой проект находится в методических указаниях под номером "1".

Занятия в 11.56 или первая лекция в 12.44

** Преподаватель
Владимир Иванович Анисимов
vanisimov2015@mail.ru

vianosimov2005.narod.ru

* Инженерная компьютерная графика
Владимир Николаевич Вересов
vnveresov@etu.ru

www.eltech.ru ФИБС ПМИГ читаемые дисциплины "Инженерная графика"

Вар 1-40

Компас граффисекский процессор АСКОН, "Компас"

Большаков В.П.
Инженерная и компьютерная графика

Спб.Bhv.2004

Сдать 8 файлов к концу октября

1. Отправить задание по электронке

2. номер группы и свою фамилия и номер варианта

пример на доске факультета

Можно приходить на консультации

3 контрольные работы в январе после экзамен

содержимиые билетов при сдаче курсовой работы

Номер аудитории, консультация 5576 по ср. с 18:00

* Преподаватель информатики и информационной технологии

** До начала семестра будут выданы карточки с логином и паролем
http://eplace.elthech.ru

** информатика ОФ для неаудентифированных пользователей

контрольные работы в .doc файлах в разделе библиотеке в разделе первый семестр с курсомы лекций и контрольными работами

тем у кого информатика только одну контрольную работу, которая сдается на первой лекции в январе

2 контрольные для информационной технологии без разница какой вариант

ближе к ноябрю нужно пройти "входной тест удаленно"

*** Раздел объявления на сайте
1. когда вы получаете доступ к тесту
2. последователь действий

** Пройти тесты до начала обучения

Если мало балов по рез. тестов, то на рельтат он не влияет

Одна попытка удаленно

Работать с автономного устройства, так как результы не сохраняются при потере соединения.

* Преподаватель программирование для группы 6091

Возможно с ошибкой
s_v_vlasenko@mail.ru

8 921 302 83 91

c++

- операторы
- основы алгоритмизации

* Кафедра КГП история
В течении семестра сам. работы с вопросами

Доступ к экзамену в январе

ikgp_etu@mail.ru

ИКГБ 5323 полный набор материала для истории по заочной

234-67-67

Конт работа 2 варианта в зависимости от четности студентческого билета последней цифры

3 блока по 3 вопроса

** Темы

- Киевкая русь 
- Московская русь
- Императорская россия

Делать 3 вопроса из 13

до конца 19 века

на лекции в январе 20 век

на зачет вопросы по 20 веку

** Проверяют через Антиплагиат.ру

Около половины может быть совпадение

Не меньше 10000 знаков не больше 20000 (10 листов) -- всего на 3 вопроса

14 размером TimesNewRoman

** Письмо
Тема:
Материалы заочников в формате doc
Фамилия и номер группы

*** Пример
Иванов 6002

Дмитрию Никитьевичу


** Сроки
не позднее середины октярбря

месяц на подготовку

*** Перезачет

на кафедру 5323

на 1 семестре не чего не перезачитывается

* Алегебра и геометрия
Кафедра "ВМ-2" в аудидитории 3312 (рядом с деканатом).

** Задания
Абрамова Мария Николаевна
matemleti@gmail.com

*** Расписание

по ср. с 14.00 до 19.00 объяснят лаборанты

*** Задания
zao.vm-2.spb.ru

папка 1 курс 1 семестр

**** материалы
2 контрольные работы в соответствии с сроками

вариант как в зач. книжке 

**** методички
по ком.

**** Результаты
Присылать на почту или
3312 ящик с контрольными работами

*** Вопросы
Либо к преподавателю (см. выше), либо Казакевич Виктория Григорьевна

По вторникам и четвергам

*** 1 семестр
- комплексные числа
- матрицы
- векторная алгебра
- математический анализ

*** Количество лекций

10-12 лекций всего.

*** Тест и экзамен
Тест из 5 задач в аудитории лично.

Допуск на экзамен после результатов теста.

4 задачи практические и 1 вопрос по теории.

Сдать контрольные до факта начала сессии.

* Преподаватель физической химии

лекционный курс по химии

в конце экзамен

- газовые законы
- термодинамика

** Учебники
Глинки либо Някутин

ряд задач индвидуальных дома в 2 пособиях 2005 и 2001 года

** 2005
по разделам

30 вариантов

** 2001
по табличке

** Пособия

** 2001
http://fx-let.narod.ru

eltech.chemdn.ru

** Результаты заданий

До середины ноября по адресам:

- bugrov.an@mail.ru
- alexander.n.bugrov@gmail.com

** Связь

вт. с 08.00 до 12.00
ср. с 08.00 до 12.00
  
с 09.00 до 12

с 20.00 до 22.00

корпус 5 аудитория 5575
  
* Заметки
Деканат факультета расписание уроков (лекций) по дисциплино.

40 вариантов.

Оплата до 1 февраля.

** Документы
Взять студентческую книжку.

Библиотека.

* Вопросы
За месяц до начала сессии.
