#+TITLE: Комплексные числа
* Определение

*Комплексное число* - это число, которое может быть выражено в форме $a + bi$
- $a$ и $b$ - /вещественные числа/
- $i$ - /мнимая единица/, которая удовлетворяет равенство $i^2=-1$.

* Формы представления
** Алгебраическая

$z$ - это комплексное число.

$z=x+iy$

$x, y \in {\rm I\!R}$

*** Части комплексного числа

**** Вещественная
$x = \Re\left(z\right)$

**** Мнимая
$y=\operatorname{Im} z$

*** Мнимая единица
$i^2=-1$

$\sqrt{-1}=i$

$\sqrt{-1}=-i$

*** Примеры

**** Пример возведения $i$ в различные степени
$i^1 = i$

$i^2 = -1$

$i^3 = i^2 \times i = (-1) \times i = -i$

$i^4 = i^3 \times i = -i \times i = -i^2 = 1$

$i^5 = i^4 \times i = 1 \times i = i$

***** Обобщение результата
\begin{equation}
i^n =
\begin{cases}
 1,n = 4k,     k \in \mathbb{Z}\\
 i,n = 4k + 1, k \in \mathbb{Z}\\
-1,n = 4k + 2, k \in \mathbb{Z}\\
-i,n = 4k + 3, k \in \mathbb{Z}\\
\end{cases}
\end{equation}

Действия над комплексными числами в алгебраической форме производятся по правилам действия над многочленами относительно величины $i$,
при этом важно помнить, что $i^2 = -1$.


*** TODO Дополнение
*Сумма и произведение* /комплексных чисел/ могут быть вычислены непосредственным суммированием и перемножением таких выражений,
как обычно раскрывая скобки и приводя подобные,
чтобы представить результат тоже в стандартной форме
(при этом надо учесть, что $i^2=-1$):
**** Сумма
$\left( a+ib \right) + \left( c+id \right) = \left( a+c \right) + i \left( b+d \right)$;
**** Произведение
$\left( a+ib \right) \cdot \left( c+id \right) = ac+iad+ibc+i^2bd = ac+iad+ibc-bd = \left( ac-bd \right) + i \left( ad+bc \right)$.

** TODO Тригонометрическая

Если вещественную $x$ и мнимую $y$ части комплексного числа выразить через модуль $r = \left| z \right|$ и аргумент $\varphi$ (то есть $x=r\cos\varphi$, $y=r\sin\varphi$),
то всякое комплексное число $z$, кроме нуля, можно записать в /тригонометрической форме/:

$z=r \left( \cos\varphi + i\sin\varphi \right)$.

** TODO Показательная

Применяя /формулу Эйлера/ к тригонометрической форме,
получим показательную форму комплексного числа:

$z=re^{i\varphi}$,

где $e^{i\varphi}$ - это расширение /экспоненты/ для случая комплексного показателя степени.

Отсюда вытекают следующие широко используемые равенства:
- $\cos\varphi=\frac{ \left(e^{i\varphi}+e^{-i\varphi}\right)}{2}$
- $\quad\sin\varphi=\frac{\left(e^{i\varphi}-e^{-i\varphi}\right)}{2i}$

** Действия над ними

*** Сложение и умножение комплексных чисел в алгебраической форме
**** Пример 1

***** Дано
(5 + 3i) + (-2 - i)

***** Задание
Выполнить действия

***** Решение
1. $5 + 3i - 2 -1i$
2. $(5 - 2) + (3 - 1)i$
3. $3 + 2i$

***** Ответ
$3 + 2i$

**** Пример 2

***** Дано
$2(3 + 4i) + (5 - 3i)(1 + 2i)$

***** Задание
Выполнить действия

***** Решение
1. Раскрываем скобки, пользуясь правилами действий над многочленами:
   1. $2 \times 3 + 2 \times 4i + 5 \times 1 + 5 \times 2i - 3i \times 1 - 3i \times 2i$
   2. Учитывая то, что $i \times i = i^2 = -1$
      1. $6 + 8i + 5 + 10i - 3i + 6$
      2. $6 + 5 + 6 + (8 + 10 - 3)i$
      3. $17 + 15i$
***** Ответ
$17 + 15i$
**** Пример 3

***** Дано
$(1 + 2i)x + (3 - 5i)y = 1 - 3i$

***** Найти
Найти вещественные $x$ и $y$ из данного равенства.

***** Решение
- Раскрываем скобки, пользуясь правилами действий на многочленами:
$x + 2ix + 3y - 5iy = 1 - 3i$
- Группируем вещественные и мнимые части равенства:
$(x + 3y) + (2x - 5y)i = 1 - 3i$
- Используя определения равенства комплексных чисел, приравниваем вещественные и мнимые части левой и правой частей равенства:
\begin{equation*}
\begin{cases}
 x + 3y = 1\\
2x - 5y = -3
\end{cases}
\iff
\begin{cases}
x = 1 - 3y\\
2 - 6y - 5y = -3
\end{cases}
\iff
\begin{cases}
x = 1 - 3y \\
-11y = -5
\end{cases}
\iff
\begin{cases}
x = 1 - 3 \times \frac{5}{11} \\
y = \frac{5}{11}
\end{cases}
\iff
\begin{cases}
x = -\frac{4}{11}
y = \frac{5}{11}
\end{cases}
\end{equation*}
  
***** Ответ
$x = -\frac{4}{11}$
  
$y = \frac{5}{11}$


*** Деление комплексных чисел в алгебраической форме
Комплексное число $\bar w = x - yi$ называется сопряженным числом по отношению $w = x + yi$.

**** Примеры
- $-1 + 5i$
  
- $-1 - 5i$
  
- $2 - 3i$
  
- $2 + 3i$

**** Деление

Для деления двух комплексных чисел в алгебраической форме, как правило, удобно числитель и знаменатель дроби домножать на число, сопряженное знаменателю.

***** Примеры

****** 1

******* Дано
$\frac{4 - i}{1 - 2i}$

******* Найти
Выполнить деление

******* Решение

******** Домножаем числитель и знаменатель дроби на число, сопряженное знаменателю
$\frac{(4 - i)(1 + 2i)}{(1 - 2i)(1 + 2i)}$

$\frac{4 + 8i - i - 2i^2}{1+4}$

$\frac{6 + 7i}{5}$

$\frac{6}{5} + \frac{7}{5}i$

********* Внимание
$\frac{6 + 7i}{5}$ - это выражение, а не число, поэтому его нельзя рассматривать как ответ.

******* Ответ
** TODO [5. Гл.VI ]
